// data.js - All mock data for dashboard builder POC

// GitHub Actions - CI/CD Pipeline Data
export const githubActionsData = [
  {
    name: "May 1",
    deployments: 4,
    successRate: 100,
    buildTimeMinutes: 12.3,
    testsRun: 1247,
  },
  {
    name: "May 2",
    deployments: 6,
    successRate: 83.3,
    buildTimeMinutes: 15.7,
    testsRun: 1456,
  },
  {
    name: "May 3",
    deployments: 3,
    successRate: 100,
    buildTimeMinutes: 11.2,
    testsRun: 1123,
  },
  {
    name: "May 4",
    deployments: 2,
    successRate: 100,
    buildTimeMinutes: 9.8,
    testsRun: 987,
  },
  {
    name: "May 5",
    deployments: 8,
    successRate: 87.5,
    buildTimeMinutes: 18.4,
    testsRun: 1678,
  },
  {
    name: "May 6",
    deployments: 5,
    successRate: 100,
    buildTimeMinutes: 13.1,
    testsRun: 1334,
  },
  {
    name: "May 7",
    deployments: 7,
    successRate: 85.7,
    buildTimeMinutes: 16.9,
    testsRun: 1589,
  },
  {
    name: "May 8",
    deployments: 3,
    successRate: 100,
    buildTimeMinutes: 10.5,
    testsRun: 1078,
  },
  {
    name: "May 9",
    deployments: 4,
    successRate: 100,
    buildTimeMinutes: 12.7,
    testsRun: 1298,
  },
  {
    name: "May 10",
    deployments: 1,
    successRate: 100,
    buildTimeMinutes: 8.2,
    testsRun: 756,
  },
  {
    name: "May 11",
    deployments: 2,
    successRate: 100,
    buildTimeMinutes: 9.1,
    testsRun: 892,
  },
  {
    name: "May 12",
    deployments: 9,
    successRate: 77.8,
    buildTimeMinutes: 21.3,
    testsRun: 1876,
  },
  {
    name: "May 13",
    deployments: 6,
    successRate: 83.3,
    buildTimeMinutes: 14.8,
    testsRun: 1467,
  },
  {
    name: "May 14",
    deployments: 4,
    successRate: 100,
    buildTimeMinutes: 11.9,
    testsRun: 1189,
  },
  {
    name: "May 15",
    deployments: 12,
    successRate: 75.0,
    buildTimeMinutes: 25.6,
    testsRun: 2134,
  },
  {
    name: "May 16",
    deployments: 5,
    successRate: 100,
    buildTimeMinutes: 13.4,
    testsRun: 1298,
  },
  {
    name: "May 17",
    deployments: 1,
    successRate: 100,
    buildTimeMinutes: 7.9,
    testsRun: 723,
  },
  {
    name: "May 18",
    deployments: 2,
    successRate: 100,
    buildTimeMinutes: 8.7,
    testsRun: 834,
  },
  {
    name: "May 19",
    deployments: 7,
    successRate: 85.7,
    buildTimeMinutes: 17.2,
    testsRun: 1623,
  },
  {
    name: "May 20",
    deployments: 8,
    successRate: 87.5,
    buildTimeMinutes: 19.1,
    testsRun: 1734,
  },
  {
    name: "May 21",
    deployments: 3,
    successRate: 100,
    buildTimeMinutes: 10.8,
    testsRun: 1045,
  },
  {
    name: "May 22",
    deployments: 15,
    successRate: 66.7,
    buildTimeMinutes: 28.9,
    testsRun: 2456,
  },
  {
    name: "May 23",
    deployments: 6,
    successRate: 83.3,
    buildTimeMinutes: 15.3,
    testsRun: 1434,
  },
  {
    name: "May 24",
    deployments: 1,
    successRate: 100,
    buildTimeMinutes: 8.1,
    testsRun: 734,
  },
  {
    name: "May 25",
    deployments: 2,
    successRate: 100,
    buildTimeMinutes: 9.3,
    testsRun: 876,
  },
  {
    name: "May 26",
    deployments: 4,
    successRate: 100,
    buildTimeMinutes: 12.1,
    testsRun: 1167,
  },
  {
    name: "May 27",
    deployments: 9,
    successRate: 77.8,
    buildTimeMinutes: 20.7,
    testsRun: 1823,
  },
  {
    name: "May 28",
    deployments: 7,
    successRate: 85.7,
    buildTimeMinutes: 16.4,
    testsRun: 1578,
  },
  {
    name: "May 29",
    deployments: 11,
    successRate: 72.7,
    buildTimeMinutes: 24.2,
    testsRun: 2087,
  },
  {
    name: "May 30",
    deployments: 5,
    successRate: 100,
    buildTimeMinutes: 13.8,
    testsRun: 1356,
  },
  {
    name: "May 31",
    deployments: 3,
    successRate: 100,
    buildTimeMinutes: 11.4,
    testsRun: 1123,
  },
];

// PagerDuty - Incident Management Data
export const pagerDutyData = [
  {
    name: "May 1",
    incidents: 1,
    mttrMinutes: 45,
    criticalIncidents: 0,
    usersAffected: 120,
  },
  {
    name: "May 2",
    incidents: 3,
    mttrMinutes: 156,
    criticalIncidents: 1,
    usersAffected: 1200,
  },
  {
    name: "May 3",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 4",
    incidents: 1,
    mttrMinutes: 23,
    criticalIncidents: 0,
    usersAffected: 45,
  },
  {
    name: "May 5",
    incidents: 4,
    mttrMinutes: 203,
    criticalIncidents: 2,
    usersAffected: 2100,
  },
  {
    name: "May 6",
    incidents: 2,
    mttrMinutes: 87,
    criticalIncidents: 0,
    usersAffected: 340,
  },
  {
    name: "May 7",
    incidents: 3,
    mttrMinutes: 134,
    criticalIncidents: 1,
    usersAffected: 890,
  },
  {
    name: "May 8",
    incidents: 1,
    mttrMinutes: 34,
    criticalIncidents: 0,
    usersAffected: 78,
  },
  {
    name: "May 9",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 10",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 11",
    incidents: 1,
    mttrMinutes: 67,
    criticalIncidents: 0,
    usersAffected: 234,
  },
  {
    name: "May 12",
    incidents: 6,
    mttrMinutes: 278,
    criticalIncidents: 3,
    usersAffected: 3400,
  },
  {
    name: "May 13",
    incidents: 2,
    mttrMinutes: 123,
    criticalIncidents: 0,
    usersAffected: 567,
  },
  {
    name: "May 14",
    incidents: 1,
    mttrMinutes: 56,
    criticalIncidents: 0,
    usersAffected: 189,
  },
  {
    name: "May 15",
    incidents: 8,
    mttrMinutes: 345,
    criticalIncidents: 4,
    usersAffected: 4200,
  },
  {
    name: "May 16",
    incidents: 2,
    mttrMinutes: 89,
    criticalIncidents: 0,
    usersAffected: 456,
  },
  {
    name: "May 17",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 18",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 19",
    incidents: 3,
    mttrMinutes: 167,
    criticalIncidents: 1,
    usersAffected: 1100,
  },
  {
    name: "May 20",
    incidents: 4,
    mttrMinutes: 189,
    criticalIncidents: 1,
    usersAffected: 1340,
  },
  {
    name: "May 21",
    incidents: 1,
    mttrMinutes: 43,
    criticalIncidents: 0,
    usersAffected: 123,
  },
  {
    name: "May 22",
    incidents: 9,
    mttrMinutes: 412,
    criticalIncidents: 5,
    usersAffected: 5100,
  },
  {
    name: "May 23",
    incidents: 3,
    mttrMinutes: 134,
    criticalIncidents: 1,
    usersAffected: 890,
  },
  {
    name: "May 24",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 25",
    incidents: 1,
    mttrMinutes: 29,
    criticalIncidents: 0,
    usersAffected: 67,
  },
  {
    name: "May 26",
    incidents: 1,
    mttrMinutes: 78,
    criticalIncidents: 0,
    usersAffected: 234,
  },
  {
    name: "May 27",
    incidents: 5,
    mttrMinutes: 234,
    criticalIncidents: 2,
    usersAffected: 2200,
  },
  {
    name: "May 28",
    incidents: 3,
    mttrMinutes: 145,
    criticalIncidents: 1,
    usersAffected: 980,
  },
  {
    name: "May 29",
    incidents: 7,
    mttrMinutes: 298,
    criticalIncidents: 3,
    usersAffected: 3100,
  },
  {
    name: "May 30",
    incidents: 2,
    mttrMinutes: 102,
    criticalIncidents: 0,
    usersAffected: 456,
  },
  {
    name: "May 31",
    incidents: 1,
    mttrMinutes: 45,
    criticalIncidents: 0,
    usersAffected: 178,
  },
];

// GitHub PR - Pull Request Data
export const githubPRData = [
  {
    name: "May 1",
    pullRequests: 12,
    mergeRate: 83.3,
    avgReviewTime: 4.2,
    linesChanged: 2847,
  },
  {
    name: "May 2",
    pullRequests: 18,
    mergeRate: 88.9,
    avgReviewTime: 3.8,
    linesChanged: 4156,
  },
  {
    name: "May 3",
    pullRequests: 8,
    mergeRate: 100.0,
    avgReviewTime: 2.1,
    linesChanged: 1923,
  },
  {
    name: "May 4",
    pullRequests: 6,
    mergeRate: 100.0,
    avgReviewTime: 1.8,
    linesChanged: 1456,
  },
  {
    name: "May 5",
    pullRequests: 22,
    mergeRate: 77.3,
    avgReviewTime: 5.6,
    linesChanged: 5234,
  },
  {
    name: "May 6",
    pullRequests: 15,
    mergeRate: 93.3,
    avgReviewTime: 3.2,
    linesChanged: 3456,
  },
  {
    name: "May 7",
    pullRequests: 19,
    mergeRate: 84.2,
    avgReviewTime: 4.7,
    linesChanged: 4123,
  },
  {
    name: "May 8",
    pullRequests: 9,
    mergeRate: 100.0,
    avgReviewTime: 2.3,
    linesChanged: 2134,
  },
  {
    name: "May 9",
    pullRequests: 11,
    mergeRate: 90.9,
    avgReviewTime: 3.1,
    linesChanged: 2567,
  },
  {
    name: "May 10",
    pullRequests: 4,
    mergeRate: 100.0,
    avgReviewTime: 1.5,
    linesChanged: 987,
  },
  {
    name: "May 11",
    pullRequests: 7,
    mergeRate: 100.0,
    avgReviewTime: 2.0,
    linesChanged: 1654,
  },
  {
    name: "May 12",
    pullRequests: 25,
    mergeRate: 72.0,
    avgReviewTime: 6.8,
    linesChanged: 6234,
  },
  {
    name: "May 13",
    pullRequests: 16,
    mergeRate: 87.5,
    avgReviewTime: 4.1,
    linesChanged: 3789,
  },
  {
    name: "May 14",
    pullRequests: 10,
    mergeRate: 100.0,
    avgReviewTime: 2.8,
    linesChanged: 2345,
  },
  {
    name: "May 15",
    pullRequests: 28,
    mergeRate: 67.9,
    avgReviewTime: 7.2,
    linesChanged: 7123,
  },
  {
    name: "May 16",
    pullRequests: 14,
    mergeRate: 92.9,
    avgReviewTime: 3.5,
    linesChanged: 3234,
  },
  {
    name: "May 17",
    pullRequests: 3,
    mergeRate: 100.0,
    avgReviewTime: 1.2,
    linesChanged: 756,
  },
  {
    name: "May 18",
    pullRequests: 5,
    mergeRate: 100.0,
    avgReviewTime: 1.7,
    linesChanged: 1234,
  },
  {
    name: "May 19",
    pullRequests: 20,
    mergeRate: 80.0,
    avgReviewTime: 5.1,
    linesChanged: 4567,
  },
  {
    name: "May 20",
    pullRequests: 23,
    mergeRate: 78.3,
    avgReviewTime: 5.9,
    linesChanged: 5123,
  },
  {
    name: "May 21",
    pullRequests: 8,
    mergeRate: 100.0,
    avgReviewTime: 2.4,
    linesChanged: 1876,
  },
  {
    name: "May 22",
    pullRequests: 31,
    mergeRate: 64.5,
    avgReviewTime: 8.1,
    linesChanged: 8234,
  },
  {
    name: "May 23",
    pullRequests: 17,
    mergeRate: 88.2,
    avgReviewTime: 4.3,
    linesChanged: 3987,
  },
  {
    name: "May 24",
    pullRequests: 2,
    mergeRate: 100.0,
    avgReviewTime: 1.1,
    linesChanged: 543,
  },
  {
    name: "May 25",
    pullRequests: 6,
    mergeRate: 100.0,
    avgReviewTime: 1.9,
    linesChanged: 1345,
  },
  {
    name: "May 26",
    pullRequests: 12,
    mergeRate: 91.7,
    avgReviewTime: 3.3,
    linesChanged: 2789,
  },
  {
    name: "May 27",
    pullRequests: 24,
    mergeRate: 75.0,
    avgReviewTime: 6.2,
    linesChanged: 5678,
  },
  {
    name: "May 28",
    pullRequests: 21,
    mergeRate: 81.0,
    avgReviewTime: 5.4,
    linesChanged: 4876,
  },
  {
    name: "May 29",
    pullRequests: 27,
    mergeRate: 70.4,
    avgReviewTime: 7.6,
    linesChanged: 6789,
  },
  {
    name: "May 30",
    pullRequests: 13,
    mergeRate: 92.3,
    avgReviewTime: 3.6,
    linesChanged: 3123,
  },
  {
    name: "May 31",
    pullRequests: 9,
    mergeRate: 100.0,
    avgReviewTime: 2.5,
    linesChanged: 2134,
  },
];
