// data.js - All mock data for dashboard builder POC

// GitHub Actions - CI/CD Pipeline Data
export const githubActionsData = [
  {
    name: "May 1",
    deployments: 4,
    successRate: 100,
    buildTimeMinutes: 12.3,
    testsRun: 1247,
  },
  {
    name: "May 2",
    deployments: 6,
    successRate: 83.3,
    buildTimeMinutes: 15.7,
    testsRun: 1456,
  },
  {
    name: "May 3",
    deployments: 3,
    successRate: 100,
    buildTimeMinutes: 11.2,
    testsRun: 1123,
  },
  {
    name: "May 4",
    deployments: 2,
    successRate: 100,
    buildTimeMinutes: 9.8,
    testsRun: 987,
  },
  {
    name: "May 5",
    deployments: 8,
    successRate: 87.5,
    buildTimeMinutes: 18.4,
    testsRun: 1678,
  },
  {
    name: "May 6",
    deployments: 5,
    successRate: 100,
    buildTimeMinutes: 13.1,
    testsRun: 1334,
  },
  {
    name: "May 7",
    deployments: 7,
    successRate: 85.7,
    buildTimeMinutes: 16.9,
    testsRun: 1589,
  },
  {
    name: "May 8",
    deployments: 3,
    successRate: 100,
    buildTimeMinutes: 10.5,
    testsRun: 1078,
  },
  {
    name: "May 9",
    deployments: 4,
    successRate: 100,
    buildTimeMinutes: 12.7,
    testsRun: 1298,
  },
  {
    name: "May 10",
    deployments: 1,
    successRate: 100,
    buildTimeMinutes: 8.2,
    testsRun: 756,
  },
  {
    name: "May 11",
    deployments: 2,
    successRate: 100,
    buildTimeMinutes: 9.1,
    testsRun: 892,
  },
  {
    name: "May 12",
    deployments: 9,
    successRate: 77.8,
    buildTimeMinutes: 21.3,
    testsRun: 1876,
  },
  {
    name: "May 13",
    deployments: 6,
    successRate: 83.3,
    buildTimeMinutes: 14.8,
    testsRun: 1467,
  },
  {
    name: "May 14",
    deployments: 4,
    successRate: 100,
    buildTimeMinutes: 11.9,
    testsRun: 1189,
  },
  {
    name: "May 15",
    deployments: 12,
    successRate: 75.0,
    buildTimeMinutes: 25.6,
    testsRun: 2134,
  },
  {
    name: "May 16",
    deployments: 5,
    successRate: 100,
    buildTimeMinutes: 13.4,
    testsRun: 1298,
  },
  {
    name: "May 17",
    deployments: 1,
    successRate: 100,
    buildTimeMinutes: 7.9,
    testsRun: 723,
  },
  {
    name: "May 18",
    deployments: 2,
    successRate: 100,
    buildTimeMinutes: 8.7,
    testsRun: 834,
  },
  {
    name: "May 19",
    deployments: 7,
    successRate: 85.7,
    buildTimeMinutes: 17.2,
    testsRun: 1623,
  },
  {
    name: "May 20",
    deployments: 8,
    successRate: 87.5,
    buildTimeMinutes: 19.1,
    testsRun: 1734,
  },
  {
    name: "May 21",
    deployments: 3,
    successRate: 100,
    buildTimeMinutes: 10.8,
    testsRun: 1045,
  },
  {
    name: "May 22",
    deployments: 15,
    successRate: 66.7,
    buildTimeMinutes: 28.9,
    testsRun: 2456,
  },
  {
    name: "May 23",
    deployments: 6,
    successRate: 83.3,
    buildTimeMinutes: 15.3,
    testsRun: 1434,
  },
  {
    name: "May 24",
    deployments: 1,
    successRate: 100,
    buildTimeMinutes: 8.1,
    testsRun: 734,
  },
  {
    name: "May 25",
    deployments: 2,
    successRate: 100,
    buildTimeMinutes: 9.3,
    testsRun: 876,
  },
  {
    name: "May 26",
    deployments: 4,
    successRate: 100,
    buildTimeMinutes: 12.1,
    testsRun: 1167,
  },
  {
    name: "May 27",
    deployments: 9,
    successRate: 77.8,
    buildTimeMinutes: 20.7,
    testsRun: 1823,
  },
  {
    name: "May 28",
    deployments: 7,
    successRate: 85.7,
    buildTimeMinutes: 16.4,
    testsRun: 1578,
  },
  {
    name: "May 29",
    deployments: 11,
    successRate: 72.7,
    buildTimeMinutes: 24.2,
    testsRun: 2087,
  },
  {
    name: "May 30",
    deployments: 5,
    successRate: 100,
    buildTimeMinutes: 13.8,
    testsRun: 1356,
  },
  {
    name: "May 31",
    deployments: 3,
    successRate: 100,
    buildTimeMinutes: 11.4,
    testsRun: 1123,
  },
];

// PagerDuty - Incident Management Data
export const pagerDutyData = [
  {
    name: "May 1",
    incidents: 1,
    mttrMinutes: 45,
    criticalIncidents: 0,
    usersAffected: 120,
  },
  {
    name: "May 2",
    incidents: 3,
    mttrMinutes: 156,
    criticalIncidents: 1,
    usersAffected: 1200,
  },
  {
    name: "May 3",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 4",
    incidents: 1,
    mttrMinutes: 23,
    criticalIncidents: 0,
    usersAffected: 45,
  },
  {
    name: "May 5",
    incidents: 4,
    mttrMinutes: 203,
    criticalIncidents: 2,
    usersAffected: 2100,
  },
  {
    name: "May 6",
    incidents: 2,
    mttrMinutes: 87,
    criticalIncidents: 0,
    usersAffected: 340,
  },
  {
    name: "May 7",
    incidents: 3,
    mttrMinutes: 134,
    criticalIncidents: 1,
    usersAffected: 890,
  },
  {
    name: "May 8",
    incidents: 1,
    mttrMinutes: 34,
    criticalIncidents: 0,
    usersAffected: 78,
  },
  {
    name: "May 9",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 10",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 11",
    incidents: 1,
    mttrMinutes: 67,
    criticalIncidents: 0,
    usersAffected: 234,
  },
  {
    name: "May 12",
    incidents: 6,
    mttrMinutes: 278,
    criticalIncidents: 3,
    usersAffected: 3400,
  },
  {
    name: "May 13",
    incidents: 2,
    mttrMinutes: 123,
    criticalIncidents: 0,
    usersAffected: 567,
  },
  {
    name: "May 14",
    incidents: 1,
    mttrMinutes: 56,
    criticalIncidents: 0,
    usersAffected: 189,
  },
  {
    name: "May 15",
    incidents: 8,
    mttrMinutes: 345,
    criticalIncidents: 4,
    usersAffected: 4200,
  },
  {
    name: "May 16",
    incidents: 2,
    mttrMinutes: 89,
    criticalIncidents: 0,
    usersAffected: 456,
  },
  {
    name: "May 17",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 18",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 19",
    incidents: 3,
    mttrMinutes: 167,
    criticalIncidents: 1,
    usersAffected: 1100,
  },
  {
    name: "May 20",
    incidents: 4,
    mttrMinutes: 189,
    criticalIncidents: 1,
    usersAffected: 1340,
  },
  {
    name: "May 21",
    incidents: 1,
    mttrMinutes: 43,
    criticalIncidents: 0,
    usersAffected: 123,
  },
  {
    name: "May 22",
    incidents: 9,
    mttrMinutes: 412,
    criticalIncidents: 5,
    usersAffected: 5100,
  },
  {
    name: "May 23",
    incidents: 3,
    mttrMinutes: 134,
    criticalIncidents: 1,
    usersAffected: 890,
  },
  {
    name: "May 24",
    incidents: 0,
    mttrMinutes: 0,
    criticalIncidents: 0,
    usersAffected: 0,
  },
  {
    name: "May 25",
    incidents: 1,
    mttrMinutes: 29,
    criticalIncidents: 0,
    usersAffected: 67,
  },
  {
    name: "May 26",
    incidents: 1,
    mttrMinutes: 78,
    criticalIncidents: 0,
    usersAffected: 234,
  },
  {
    name: "May 27",
    incidents: 5,
    mttrMinutes: 234,
    criticalIncidents: 2,
    usersAffected: 2200,
  },
  {
    name: "May 28",
    incidents: 3,
    mttrMinutes: 145,
    criticalIncidents: 1,
    usersAffected: 980,
  },
  {
    name: "May 29",
    incidents: 7,
    mttrMinutes: 298,
    criticalIncidents: 3,
    usersAffected: 3100,
  },
  {
    name: "May 30",
    incidents: 2,
    mttrMinutes: 102,
    criticalIncidents: 0,
    usersAffected: 456,
  },
  {
    name: "May 31",
    incidents: 1,
    mttrMinutes: 45,
    criticalIncidents: 0,
    usersAffected: 178,
  },
];
